<?xml version="1.0" encoding="utf-8"?><Database Name="PatientFollowUp" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-SRS9QEO\SQLEXPRESS;Initial Catalog=PatientFollowUp;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PatientFollowUpConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Operator" Member="Operators">
    <Type Name="Operator">
      <Column Name="operator_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="doctor_id" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="name_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address_" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phone_no" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Association Name="Doctor_Operator" Member="Doctor" ThisKey="doctor_id" OtherKey="doctor_id" Type="Doctor" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.Patient" Member="Patients">
    <Type Name="Patient">
      <Column Name="patient_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="name_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address_" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(70)" CanBeNull="true" />
      <Column Name="phone_no" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="medical_history" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Doctor" Member="Doctors">
    <Type Name="Doctor">
      <Column Name="doctor_id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="registration_no" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="name_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="address_" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="email" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="phone_no" Type="System.String" DbType="VarChar(1)" CanBeNull="true" />
      <Column Name="date_of_birth" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="degree" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Column Name="specialization" Type="System.String" DbType="VarChar(20)" CanBeNull="true" />
      <Column Name="work_address_" Type="System.String" DbType="VarChar(50)" CanBeNull="true" />
      <Association Name="Doctor_Operator" Member="Operators" ThisKey="doctor_id" OtherKey="doctor_id" Type="Operator" />
    </Type>
  </Table>
  <Table Name="dbo.Login" Member="Logins">
    <Type Name="Login">
      <Column Name="userid" Type="System.String" DbType="VarChar(50) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="password_" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
    </Type>
  </Table>
  <Function Name="dbo.SP_OPERATOR" Method="SP_OPERATOR">
    <Parameter Name="ACTION" Parameter="aCTION" Type="System.Int32" DbType="Int" />
    <Parameter Name="operator_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="doctor_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name_" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address_" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phone_no" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="date_of_birth" Type="System.DateTime" DbType="Date" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PATIENT" Method="SP_PATIENT">
    <Parameter Name="ACTION" Parameter="aCTION" Type="System.Int32" DbType="Int" />
    <Parameter Name="patient_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="name_" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address_" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(70)" />
    <Parameter Name="phone_no" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="date_of_birth" Type="System.DateTime" DbType="Date" />
    <Parameter Name="medical_history" Type="System.String" DbType="VarChar(100)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_PAYMENT" Method="SP_PAYMENT">
    <Parameter Name="ACTION" Parameter="aCTION" Type="System.Int32" DbType="Int" />
    <Parameter Name="payment_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="payment_mode" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="payment_date" Type="System.DateTime" DbType="Date" />
    <Parameter Name="payment_status" Type="System.String" DbType="VarChar(20)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_DOCTOR" Method="SP_DOCTOR">
    <Parameter Name="ACTION" Parameter="aCTION" Type="System.Int32" DbType="Int" />
    <Parameter Name="doctor_id" Type="System.Int32" DbType="Int" />
    <Parameter Name="registration_no" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="name_" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="address_" Type="System.String" DbType="VarChar(100)" />
    <Parameter Name="email" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="phone_no" Type="System.String" DbType="VarChar(1)" />
    <Parameter Name="date_of_birth" Type="System.DateTime" DbType="Date" />
    <Parameter Name="degree" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="specialization" Type="System.String" DbType="VarChar(20)" />
    <Parameter Name="work_address_" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.SP_LOGIN" Method="SP_LOGIN">
    <Parameter Name="ACTION" Parameter="aCTION" Type="System.Int32" DbType="Int" />
    <Parameter Name="USERID" Parameter="uSERID" Type="System.String" DbType="VarChar(50)" />
    <Parameter Name="PASSWORD_" Parameter="pASSWORD_" Type="System.String" DbType="VarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>