#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="PatientFollowUp")]
public partial class DataClassesDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertOperator(Operator instance);
  partial void UpdateOperator(Operator instance);
  partial void DeleteOperator(Operator instance);
  partial void InsertPatient(Patient instance);
  partial void UpdatePatient(Patient instance);
  partial void DeletePatient(Patient instance);
  partial void InsertDoctor(Doctor instance);
  partial void UpdateDoctor(Doctor instance);
  partial void DeleteDoctor(Doctor instance);
  partial void InsertLogin(Login instance);
  partial void UpdateLogin(Login instance);
  partial void DeleteLogin(Login instance);
  #endregion
	
	public DataClassesDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["PatientFollowUpConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<Operator> Operators
	{
		get
		{
			return this.GetTable<Operator>();
		}
	}
	
	public System.Data.Linq.Table<Patient> Patients
	{
		get
		{
			return this.GetTable<Patient>();
		}
	}
	
	public System.Data.Linq.Table<Doctor> Doctors
	{
		get
		{
			return this.GetTable<Doctor>();
		}
	}
	
	public System.Data.Linq.Table<Login> Logins
	{
		get
		{
			return this.GetTable<Login>();
		}
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_OPERATOR")]
	public int SP_OPERATOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> operator_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> doctor_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string address_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string phone_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date_of_birth)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, operator_id, doctor_id, name_, address_, email, phone_no, date_of_birth);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PATIENT")]
	public int SP_PATIENT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> patient_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string address_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(70)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string phone_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date_of_birth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string medical_history)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, patient_id, name_, address_, email, phone_no, date_of_birth, medical_history);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_PAYMENT")]
	public int SP_PAYMENT([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> payment_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string payment_mode, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> payment_date, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string payment_status)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, payment_id, payment_mode, payment_date, payment_status);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_DOCTOR")]
	public int SP_DOCTOR([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> doctor_id, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string registration_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string name_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(100)")] string address_, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string email, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(1)")] string phone_no, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> date_of_birth, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string degree, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(20)")] string specialization, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="VarChar(50)")] string work_address_)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, doctor_id, registration_no, name_, address_, email, phone_no, date_of_birth, degree, specialization, work_address_);
		return ((int)(result.ReturnValue));
	}
	
	[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SP_LOGIN")]
	public int SP_LOGIN([global::System.Data.Linq.Mapping.ParameterAttribute(Name="ACTION", DbType="Int")] System.Nullable<int> aCTION, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="USERID", DbType="VarChar(50)")] string uSERID, [global::System.Data.Linq.Mapping.ParameterAttribute(Name="PASSWORD_", DbType="VarChar(50)")] string pASSWORD_)
	{
		IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), aCTION, uSERID, pASSWORD_);
		return ((int)(result.ReturnValue));
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Operator")]
public partial class Operator : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _operator_id;
	
	private System.Nullable<int> _doctor_id;
	
	private string _name_;
	
	private string _address_;
	
	private string _email;
	
	private string _phone_no;
	
	private System.Nullable<System.DateTime> _date_of_birth;
	
	private EntityRef<Doctor> _Doctor;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onoperator_idChanging(int value);
    partial void Onoperator_idChanged();
    partial void Ondoctor_idChanging(System.Nullable<int> value);
    partial void Ondoctor_idChanged();
    partial void Onname_Changing(string value);
    partial void Onname_Changed();
    partial void Onaddress_Changing(string value);
    partial void Onaddress_Changed();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onphone_noChanging(string value);
    partial void Onphone_noChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    #endregion
	
	public Operator()
	{
		this._Doctor = default(EntityRef<Doctor>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_operator_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int operator_id
	{
		get
		{
			return this._operator_id;
		}
		set
		{
			if ((this._operator_id != value))
			{
				this.Onoperator_idChanging(value);
				this.SendPropertyChanging();
				this._operator_id = value;
				this.SendPropertyChanged("operator_id");
				this.Onoperator_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctor_id", DbType="Int")]
	public System.Nullable<int> doctor_id
	{
		get
		{
			return this._doctor_id;
		}
		set
		{
			if ((this._doctor_id != value))
			{
				if (this._Doctor.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.Ondoctor_idChanging(value);
				this.SendPropertyChanging();
				this._doctor_id = value;
				this.SendPropertyChanged("doctor_id");
				this.Ondoctor_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_", DbType="VarChar(50)")]
	public string name_
	{
		get
		{
			return this._name_;
		}
		set
		{
			if ((this._name_ != value))
			{
				this.Onname_Changing(value);
				this.SendPropertyChanging();
				this._name_ = value;
				this.SendPropertyChanged("name_");
				this.Onname_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_", DbType="VarChar(100)")]
	public string address_
	{
		get
		{
			return this._address_;
		}
		set
		{
			if ((this._address_ != value))
			{
				this.Onaddress_Changing(value);
				this.SendPropertyChanging();
				this._address_ = value;
				this.SendPropertyChanged("address_");
				this.Onaddress_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_no", DbType="VarChar(1)")]
	public string phone_no
	{
		get
		{
			return this._phone_no;
		}
		set
		{
			if ((this._phone_no != value))
			{
				this.Onphone_noChanging(value);
				this.SendPropertyChanging();
				this._phone_no = value;
				this.SendPropertyChanged("phone_no");
				this.Onphone_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date")]
	public System.Nullable<System.DateTime> date_of_birth
	{
		get
		{
			return this._date_of_birth;
		}
		set
		{
			if ((this._date_of_birth != value))
			{
				this.Ondate_of_birthChanging(value);
				this.SendPropertyChanging();
				this._date_of_birth = value;
				this.SendPropertyChanged("date_of_birth");
				this.Ondate_of_birthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doctor_Operator", Storage="_Doctor", ThisKey="doctor_id", OtherKey="doctor_id", IsForeignKey=true, DeleteRule="CASCADE")]
	public Doctor Doctor
	{
		get
		{
			return this._Doctor.Entity;
		}
		set
		{
			Doctor previousValue = this._Doctor.Entity;
			if (((previousValue != value) 
						|| (this._Doctor.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._Doctor.Entity = null;
					previousValue.Operators.Remove(this);
				}
				this._Doctor.Entity = value;
				if ((value != null))
				{
					value.Operators.Add(this);
					this._doctor_id = value.doctor_id;
				}
				else
				{
					this._doctor_id = default(Nullable<int>);
				}
				this.SendPropertyChanged("Doctor");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Patient")]
public partial class Patient : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _patient_id;
	
	private string _name_;
	
	private string _address_;
	
	private string _email;
	
	private string _phone_no;
	
	private System.Nullable<System.DateTime> _date_of_birth;
	
	private string _medical_history;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpatient_idChanging(int value);
    partial void Onpatient_idChanged();
    partial void Onname_Changing(string value);
    partial void Onname_Changed();
    partial void Onaddress_Changing(string value);
    partial void Onaddress_Changed();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onphone_noChanging(string value);
    partial void Onphone_noChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    partial void Onmedical_historyChanging(string value);
    partial void Onmedical_historyChanged();
    #endregion
	
	public Patient()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_patient_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int patient_id
	{
		get
		{
			return this._patient_id;
		}
		set
		{
			if ((this._patient_id != value))
			{
				this.Onpatient_idChanging(value);
				this.SendPropertyChanging();
				this._patient_id = value;
				this.SendPropertyChanged("patient_id");
				this.Onpatient_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_", DbType="VarChar(50)")]
	public string name_
	{
		get
		{
			return this._name_;
		}
		set
		{
			if ((this._name_ != value))
			{
				this.Onname_Changing(value);
				this.SendPropertyChanging();
				this._name_ = value;
				this.SendPropertyChanged("name_");
				this.Onname_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_", DbType="VarChar(100)")]
	public string address_
	{
		get
		{
			return this._address_;
		}
		set
		{
			if ((this._address_ != value))
			{
				this.Onaddress_Changing(value);
				this.SendPropertyChanging();
				this._address_ = value;
				this.SendPropertyChanged("address_");
				this.Onaddress_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(70)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_no", DbType="VarChar(1)")]
	public string phone_no
	{
		get
		{
			return this._phone_no;
		}
		set
		{
			if ((this._phone_no != value))
			{
				this.Onphone_noChanging(value);
				this.SendPropertyChanging();
				this._phone_no = value;
				this.SendPropertyChanged("phone_no");
				this.Onphone_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date")]
	public System.Nullable<System.DateTime> date_of_birth
	{
		get
		{
			return this._date_of_birth;
		}
		set
		{
			if ((this._date_of_birth != value))
			{
				this.Ondate_of_birthChanging(value);
				this.SendPropertyChanging();
				this._date_of_birth = value;
				this.SendPropertyChanged("date_of_birth");
				this.Ondate_of_birthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_medical_history", DbType="VarChar(100)")]
	public string medical_history
	{
		get
		{
			return this._medical_history;
		}
		set
		{
			if ((this._medical_history != value))
			{
				this.Onmedical_historyChanging(value);
				this.SendPropertyChanging();
				this._medical_history = value;
				this.SendPropertyChanged("medical_history");
				this.Onmedical_historyChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Doctor")]
public partial class Doctor : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _doctor_id;
	
	private string _registration_no;
	
	private string _name_;
	
	private string _address_;
	
	private string _email;
	
	private string _phone_no;
	
	private System.Nullable<System.DateTime> _date_of_birth;
	
	private string _degree;
	
	private string _specialization;
	
	private string _work_address_;
	
	private EntitySet<Operator> _Operators;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Ondoctor_idChanging(int value);
    partial void Ondoctor_idChanged();
    partial void Onregistration_noChanging(string value);
    partial void Onregistration_noChanged();
    partial void Onname_Changing(string value);
    partial void Onname_Changed();
    partial void Onaddress_Changing(string value);
    partial void Onaddress_Changed();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void Onphone_noChanging(string value);
    partial void Onphone_noChanged();
    partial void Ondate_of_birthChanging(System.Nullable<System.DateTime> value);
    partial void Ondate_of_birthChanged();
    partial void OndegreeChanging(string value);
    partial void OndegreeChanged();
    partial void OnspecializationChanging(string value);
    partial void OnspecializationChanged();
    partial void Onwork_address_Changing(string value);
    partial void Onwork_address_Changed();
    #endregion
	
	public Doctor()
	{
		this._Operators = new EntitySet<Operator>(new Action<Operator>(this.attach_Operators), new Action<Operator>(this.detach_Operators));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_doctor_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int doctor_id
	{
		get
		{
			return this._doctor_id;
		}
		set
		{
			if ((this._doctor_id != value))
			{
				this.Ondoctor_idChanging(value);
				this.SendPropertyChanging();
				this._doctor_id = value;
				this.SendPropertyChanged("doctor_id");
				this.Ondoctor_idChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_registration_no", DbType="VarChar(20)")]
	public string registration_no
	{
		get
		{
			return this._registration_no;
		}
		set
		{
			if ((this._registration_no != value))
			{
				this.Onregistration_noChanging(value);
				this.SendPropertyChanging();
				this._registration_no = value;
				this.SendPropertyChanged("registration_no");
				this.Onregistration_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_name_", DbType="VarChar(50)")]
	public string name_
	{
		get
		{
			return this._name_;
		}
		set
		{
			if ((this._name_ != value))
			{
				this.Onname_Changing(value);
				this.SendPropertyChanging();
				this._name_ = value;
				this.SendPropertyChanged("name_");
				this.Onname_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_address_", DbType="VarChar(100)")]
	public string address_
	{
		get
		{
			return this._address_;
		}
		set
		{
			if ((this._address_ != value))
			{
				this.Onaddress_Changing(value);
				this.SendPropertyChanging();
				this._address_ = value;
				this.SendPropertyChanged("address_");
				this.Onaddress_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50)")]
	public string email
	{
		get
		{
			return this._email;
		}
		set
		{
			if ((this._email != value))
			{
				this.OnemailChanging(value);
				this.SendPropertyChanging();
				this._email = value;
				this.SendPropertyChanged("email");
				this.OnemailChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone_no", DbType="VarChar(1)")]
	public string phone_no
	{
		get
		{
			return this._phone_no;
		}
		set
		{
			if ((this._phone_no != value))
			{
				this.Onphone_noChanging(value);
				this.SendPropertyChanging();
				this._phone_no = value;
				this.SendPropertyChanged("phone_no");
				this.Onphone_noChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_date_of_birth", DbType="Date")]
	public System.Nullable<System.DateTime> date_of_birth
	{
		get
		{
			return this._date_of_birth;
		}
		set
		{
			if ((this._date_of_birth != value))
			{
				this.Ondate_of_birthChanging(value);
				this.SendPropertyChanging();
				this._date_of_birth = value;
				this.SendPropertyChanged("date_of_birth");
				this.Ondate_of_birthChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_degree", DbType="VarChar(50)")]
	public string degree
	{
		get
		{
			return this._degree;
		}
		set
		{
			if ((this._degree != value))
			{
				this.OndegreeChanging(value);
				this.SendPropertyChanging();
				this._degree = value;
				this.SendPropertyChanged("degree");
				this.OndegreeChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_specialization", DbType="VarChar(20)")]
	public string specialization
	{
		get
		{
			return this._specialization;
		}
		set
		{
			if ((this._specialization != value))
			{
				this.OnspecializationChanging(value);
				this.SendPropertyChanging();
				this._specialization = value;
				this.SendPropertyChanged("specialization");
				this.OnspecializationChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_work_address_", DbType="VarChar(50)")]
	public string work_address_
	{
		get
		{
			return this._work_address_;
		}
		set
		{
			if ((this._work_address_ != value))
			{
				this.Onwork_address_Changing(value);
				this.SendPropertyChanging();
				this._work_address_ = value;
				this.SendPropertyChanged("work_address_");
				this.Onwork_address_Changed();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Doctor_Operator", Storage="_Operators", ThisKey="doctor_id", OtherKey="doctor_id")]
	public EntitySet<Operator> Operators
	{
		get
		{
			return this._Operators;
		}
		set
		{
			this._Operators.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_Operators(Operator entity)
	{
		this.SendPropertyChanging();
		entity.Doctor = this;
	}
	
	private void detach_Operators(Operator entity)
	{
		this.SendPropertyChanging();
		entity.Doctor = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Login")]
public partial class Login : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private string _userid;
	
	private string _password_;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnuseridChanging(string value);
    partial void OnuseridChanged();
    partial void Onpassword_Changing(string value);
    partial void Onpassword_Changed();
    #endregion
	
	public Login()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_userid", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
	public string userid
	{
		get
		{
			return this._userid;
		}
		set
		{
			if ((this._userid != value))
			{
				this.OnuseridChanging(value);
				this.SendPropertyChanging();
				this._userid = value;
				this.SendPropertyChanged("userid");
				this.OnuseridChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password_", DbType="VarChar(30)")]
	public string password_
	{
		get
		{
			return this._password_;
		}
		set
		{
			if ((this._password_ != value))
			{
				this.Onpassword_Changing(value);
				this.SendPropertyChanging();
				this._password_ = value;
				this.SendPropertyChanged("password_");
				this.Onpassword_Changed();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
